{% set name = "modal-client" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/modal/modal-{{ version }}.tar.gz
  sha256: 190ea96d45fbdfd6d6cb545a736bf1ef5599511d346ae94cfd773528a33b6097

build:
  entry_points:
    - modal = modal.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp
    - certifi
    - click >=8.1.0,<8.2.dev0
    - grpclib ==0.4.7
    - protobuf >=3.19,<7.0,!=4.24.0
    - rich >=12.0.0
    - synchronicity >=0.9.12,<0.10.dev0
    - toml
    - typer >=0.9
    - types-certifi
    - types-toml
    - watchfiles
    - typing_extensions >=4.6,<5.dev0

test:
  imports:
    - modal
    - modal_proto
    - modal_version
  commands:
    - pip check
    - modal --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/modal/
  summary: Python client library for Modal
  dev_url: https://github.com/modal-labs/modal-client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thomasjpfan
    - devennavani
    - aksh-at
    - erikbern
    - freider
    - mwaskom
