{% set name = "modal-client" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/modal/modal-{{ version }}.tar.gz
  sha256: d80fd98ce7729405546252b7a6729baf3a9cb22b80d303779b0c0d48b9af3397

build:
  entry_points:
    - modal = modal.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp
    - certifi
    - click >=8.1.0,<8.2.dev0
    - grpclib >=0.4.7,<0.4.10
    - protobuf >=3.19,<7.0,!=4.24.0
    - rich >=12.0.0
    - synchronicity >=0.11.1,<0.12.0
    - toml
    - typer >=0.9
    - types-certifi
    - types-toml
    - watchfiles
    - typing_extensions >=4.6,<5.dev0
    - cbor2

test:
  imports:
    - modal
    - modal_proto
    - modal_version
  commands:
    - pip check
    - modal --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/modal/
  summary: Python client library for Modal
  dev_url: https://github.com/modal-labs/modal-client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thomasjpfan
    - devennavani
    - aksh-at
    - erikbern
    - freider
    - mwaskom
